import type { NextPage } from "next";
import Head from "next/head";
import Header from "../header";

const Template: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {children}
      </main>
    </>
  );
};

export default Template;
